
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ubiratan
 */
public class TelaTabela extends javax.swing.JFrame {
    ArrayList<Atomica> atomicas = new ArrayList();
    String phi ;
    String[] form;
    Leitor leitor; 
    Tabela tabela; 
    /**
     * Creates new form FrameTabela
     */
    public TelaTabela( String phi, ArrayList<Atomica> ato) {
       /* initComponents();
        this.phi = phi;
        this.form  = phi.split("");
        this.atomicas = ato;
        this.leitor =  new Leitor(phi);
        this.tabela = new Tabela(this.leitor.lerFormula(this.form, 0, this.form.length ), this.atomicas);
    
        this.setTitle("Calculadora de Valorações Lógicas");
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        initComponents();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
