
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ubiratan
 */
public class TelaVal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaVal
     */
    public TelaVal() {
        initComponents();
        initalEnabledComponents();
        this.setTitle("Calculadora de Valorações Lógicas");
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void habilita(){
        setVariaveis(true);
        setConectivos(true);
        pAb.setEnabled(true);
        pFc.setEnabled(true);
        
        
    }
    
   void setVariaveis(boolean valor){
        pAb.setEnabled(valor);
        btA.setEnabled(valor);
        btB.setEnabled(valor);
        btC.setEnabled(valor);
        btD.setEnabled(valor);
        btE.setEnabled(valor);
        btNeg.setEnabled(valor); 
  //      System.out.println(verParent());
        if(verParent()){
            pFc.setEnabled(false);
            calcular.setEnabled(true);  
        }else
            pFc.setEnabled(true);
    }
    
    private void setConectivos(boolean valor){
        btAnd.setEnabled(valor);
        btOr.setEnabled(valor);
        btNeg.setEnabled(valor);
        pFc.setEnabled(valor);
        if(verParent())
            calcular.setEnabled(false);  
       
           
    }
    
    private void tratamento(String tipo){
        String key = tipo;
     //   System.out.println(tipo);
        habilita();
        switch (key){
            case "'":
                setConectivos(true);
                setVariaveis(false);
               
                break;
            case "(":              
                btNeg.setEnabled(false);  
                pFc.setEnabled(false);
                btAnd.setEnabled(false);
                btOr.setEnabled(false);                
                calcular.setEnabled(false);
                break;
            case ")":
                pAb.setEnabled(false);
                setVariaveis(false);
                if(verParent())
                    calcular.setEnabled(true);
                else
                    calcular.setEnabled(false);
                 btNeg.setEnabled(true); 
                break;
            case "+":
                setVariaveis(true);
                setConectivos(false);
                break;
            case ".":             
                setVariaveis(true);
                setConectivos(false);
                break;
            case "A":        
                setConectivos(true);
                setVariaveis(false);
                break;
            case "B":
                              
                setConectivos(true);
                setVariaveis(false);
                break;
            case "C":
             
                setConectivos(true);
                setVariaveis(false);
                break;
            case "D":
                setConectivos(true);
                setVariaveis(false);
                break;
            case "E":               
                setConectivos(true);
                setVariaveis(false);
                break;
        }
    }
    
    private void initalEnabledComponents(){
        setVariaveis(true);
        pAb.setEnabled(true);
        setConectivos(false);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btOr = new javax.swing.JButton();
        btAnd = new javax.swing.JButton();
        btNeg = new javax.swing.JButton();
        pAb = new javax.swing.JButton();
        pFc = new javax.swing.JButton();
        cxTxt = new javax.swing.JTextField();
        btA = new javax.swing.JButton();
        btB = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        btE = new javax.swing.JButton();
        calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btOr.setText("+");
        btOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrActionPerformed(evt);
            }
        });

        btAnd.setText(".");
        btAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAndActionPerformed(evt);
            }
        });

        btNeg.setText("'");
        btNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNegActionPerformed(evt);
            }
        });

        pAb.setText("(");
        pAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAbActionPerformed(evt);
            }
        });

        pFc.setText(")");
        pFc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pFcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pAb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pFc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btOr)
                        .addGap(18, 18, 18)
                        .addComponent(btAnd)
                        .addGap(18, 18, 18)
                        .addComponent(btNeg)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAb)
                    .addComponent(pFc))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOr)
                    .addComponent(btAnd)
                    .addComponent(btNeg))
                .addGap(23, 23, 23))
        );

        cxTxt.setEnabled(false);

        btA.setText("A");
        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });

        btB.setText("B");
        btB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBActionPerformed(evt);
            }
        });

        btC.setText("C");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        btD.setText("D");
        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });

        btE.setText("E");
        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });

        calcular.setText("calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btA)
                                .addGap(18, 18, 18)
                                .addComponent(btB)
                                .addGap(18, 18, 18)
                                .addComponent(btC)
                                .addGap(18, 18, 18)
                                .addComponent(btD)
                                .addGap(18, 18, 18)
                                .addComponent(btE))
                            .addComponent(cxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(calcular)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(cxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btA)
                    .addComponent(btB)
                    .addComponent(btC)
                    .addComponent(btD)
                    .addComponent(btE))
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(calcular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /*casos
        caso 1 inserir pAb
            inserir quantos quiser
        caso 2 inserir pFc
            so pode inserir se pAB > pFC
    */ 
    private boolean verParent(){
        int contF = 0;
        int contA = 0;
        String[] camp = cxTxt.getText().split(""); 
        for(String a : camp) {
            if( a.equals("("))
                contA++;
            if(a.equals(")"))
                contF++;
        }
        
        if(contA > contF)
            return false;
        return true;
    }
    
    
    
    private void btOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrActionPerformed
       tratamento(btOr.getText());
       cxTxt.setText(cxTxt.getText() + btOr.getText());
       
    }//GEN-LAST:event_btOrActionPerformed
   
    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
        cxTxt.setText(cxTxt.getText() + btA.getText());
        tratamento(btA.getText());
        Atomica a  = new Atomica("A");
       // if(!atomicas.contains(a))
          //  atomicas.add(a);
    }//GEN-LAST:event_btAActionPerformed

    private void btBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBActionPerformed
        tratamento(btB.getText());
        cxTxt.setText(cxTxt.getText() + btB.getText());
        Atomica b = new Atomica("B");
        //if(!atomicas.contains(b))
          //  atomicas.add(b); 
      
    }//GEN-LAST:event_btBActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        cxTxt.setText(cxTxt.getText() + btC.getText());
        tratamento(btC.getText());
        Atomica c = new Atomica("C");
        //if(!atomicas.contains(c))
         //   atomicas.add(c);        
    }//GEN-LAST:event_btCActionPerformed

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        cxTxt.setText(cxTxt.getText() + btD.getText());
        tratamento(btD.getText());
        Atomica d = new Atomica("D");
        //if(!atomicas.contains(d))
        //    atomicas.add(d);         
    }//GEN-LAST:event_btDActionPerformed

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        cxTxt.setText(cxTxt.getText() + btE.getText());
        tratamento(btE.getText());        
        Atomica e = new Atomica("E");
       // if(!atomicas.contains(e))
          //  atomicas.add(e); 
        
    }//GEN-LAST:event_btEActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
      
           String phi = cxTxt.getText(); 
           Leitor l = new Leitor(phi);
           
           this.setVisible(false);
           FrameTeste t = new FrameTeste((Conectivo)l.lerFormula(), l.obterAtomicas(), l.stringFormula());
           t.setVisible(true);
        /* String phi = cxTxt.getText();
        String [] form = phi.split("");
        Leitor l = new Leitor(phi);
        this.setVisible(false);
        FrameTeste t = new FrameTeste(l.lerFormula(form, 0, form.length), atomicas);
        t.setVisible(true);
        
        this.setVisible(false);
        TelaTabela t = new TelaTabela(cxTxt.getText(), atomicas);
        t.setVisible(true);*/
    }//GEN-LAST:event_calcularActionPerformed

    private void btAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAndActionPerformed
       cxTxt.setText(cxTxt.getText() + btAnd.getText());
        tratamento(btAnd.getText());

    }//GEN-LAST:event_btAndActionPerformed

    private void btNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNegActionPerformed
       cxTxt.setText(cxTxt.getText() + btNeg.getText());
        tratamento(btNeg.getText());

    }//GEN-LAST:event_btNegActionPerformed

    private void pAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAbActionPerformed
       cxTxt.setText(cxTxt.getText() + pAb.getText()); 
        tratamento(pAb.getText());
          
    }//GEN-LAST:event_pAbActionPerformed

    private void pFcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pFcActionPerformed
       
       cxTxt.setText(cxTxt.getText() + pFc.getText());
       tratamento(pFc.getText());
    }//GEN-LAST:event_pFcActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA;
    private javax.swing.JButton btAnd;
    private javax.swing.JButton btB;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btE;
    private javax.swing.JButton btNeg;
    private javax.swing.JButton btOr;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cxTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pAb;
    private javax.swing.JButton pFc;
    // End of variables declaration//GEN-END:variables
}
